# Generated by Django 4.1.3 on 2022-11-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0006_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='youtube_id',
            field=models.CharField(default='1', max_length=32),
        ),
        migrations.AddField(
            model_name='modulo',
            name='descricao',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='publico',
            field=models.TextField(null=True),
        ),
    ]
